---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the web server
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  DingoInstanceType:
    Description: Enter d2.2xlarge, d2.4xlarge or d3.8xlarge. Default is d3.2xlarge.
    Type: String
    Default: d2.2xlarge
    AllowedValues:
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge

  ICRARVPCID:
    Description: ICRAR VCP ID
    Type: AWS::EC2::VPC::Id

  AlarmEmail:
    Description: Emnail address to send autoscaling alarms to
    Type: String
    Default: sliedig@amazon.com

Mappings:
  AskapSoftAMIRegionMappinfg:
    ap-southeast-2:
      'AMI': ami-0c9d48b5db609ad6e

Resources:
  DingoQueue: 
    Type: AWS::SQS::Queue
  
  AlarmTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: !Ref AlarmEmail
          Protocol: "email"

  QueueDepthAlarm: 
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmDescription: "Alarm if queue depth grows beyond 10 messages"
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions: 
        - Name: "QueueName"
          Value: !GetAtt DingoQueue.QueueName
      Statistic: "Sum"
      Period: "300"
      EvaluationPeriods: "1"
      Threshold: "10"
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions: 
        - !Ref AlarmTopic
      InsufficientDataActions: 
        - !Ref AlarmTopic

  WebServerGroup: 
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AvailabilityZones: 
        Fn::GetAZs: 
          Ref: "AWS::Region"
      LaunchConfigurationName: 
        !Ref DingoLaunchConfig
      MinSize: "1"
      MaxSize: "1"

  DingoLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sdb
          VirtualName: ephemeral0
        - DeviceName: /dev/sdc
          VirtualName: ephemeral1
        - DeviceName: /dev/sdd
          VirtualName: ephemeral2
        - DeviceName: /dev/sde
          VirtualName: ephemeral3
        - DeviceName: /dev/sdf
          VirtualName: ephemeral4
        - DeviceName: /dev/sdg
          VirtualName: ephemeral5
        - DeviceName: /dev/sdh
          VirtualName: ephemeral6
        - DeviceName: /dev/sdi
          VirtualName: ephemeral7
      IamInstanceProfile: !Ref DingoInstanceProfile
      ImageId: !FindInMap ["AskapSoftAMIRegionMappinfg", !Ref "AWS::Region", "AMI"]
      InstanceType: !Ref DingoInstanceType
      KernelId: String
      KeyName: String
      LaunchConfigurationName: String
      RamDiskId: String
      SecurityGroups:
        - !Ref DingoInstanceSecurityGroup
      # UserData:

  DingoInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: "/"
      Roles:
        - !Ref DingoRole

  DingoRole:
      Type: "AWS::IAM::Role"
      Properties: 
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "ec2.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        Path: "/"
        Policies: 
          - 
            PolicyName: "root"
            PolicyDocument: 
              Version: '2012-10-17'
              Statement:
                - 
                  Action: 's3:*'
                  Effect: Allow
                  Resource: '*'


  DingoInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref ICRARVPCID
      GroupName: dingo_instance_security_group     
      GroupDescription: Group for the DINGO code
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


  # DingoSpotFleet:
  #   Type: AWS::EC2::SpotFleet
  #   Properties: 
  #     SpotFleetRequestConfigData:
  #       SpotFleetRequestConfigData

#Outputs:
  