AWSTemplateFormatVersion: "2010-09-09"

Description: >
  A template to start the system for DINGO processing
  It consists of SQS, VPC, EC2, AutoScaling, CloudWatch

#Metadata:
#  template metadata

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the web server
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Type: String
    Default: i3.2xlarge
    AllowedValues:
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
    Description: Enter i3.xlarge, i3.2xlarge, i3.4xlarge or i3.8xlarge. Default is i3.2xlarge.

  SSHLocation:
    Description: Lockdown SSH access to the bastion host (default can be accessed from anywhere)
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.

Mappings:
  AWSRegionAMI:
    ap-southeast-2:
      'AMI': ami-43851279

Conditions:
  set of conditions

Transform:
  set of transforms

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref 'KeyName'
      InstanceType: !Ref 'InstanceType'
      ImageId: !FindInMap [AWSRegionAMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch, !Ref 'InstanceType', Arch]]
      SecurityGroups: [!Ref 'EC2SecurityGroup']
      BlockDeviceMappings:
        - DeviceName: /dev/sdb
          VirtualName: ephemeral0
        - DeviceName: /dev/sdc
          VirtualName: ephemeral1
        - DeviceName: /dev/sdd
          VirtualName: ephemeral2
        - DeviceName: /dev/sde
          VirtualName: ephemeral3
        - DeviceName: /dev/sdf
          VirtualName: ephemeral4
        - DeviceName: /dev/sdg
          VirtualName: ephemeral5
        - DeviceName: /dev/sdh
          VirtualName: ephemeral6
        - DeviceName: /dev/sdi
          VirtualName: ephemeral7

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref 'SSHLocation'

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

# SQS

# AutoScaling based on SQS queue length

# CloudWatch


Outputs:
  EC2InstanceId:
    Value: !Ref EC2Instance
    Description: Test EC2 Instance ID