---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'

Parameters:
  BranchName:
    Default: BranchName
    Description: Choose which Branch do you want to use
    Type: String
  Customer:
    Description: is used as Customer tag value for all resources
    Type: String
    Default: Customer
    AllowedPattern: ^[A-Za-z0-9]*$
    ConstraintDescription: must contain only alphanumeric characters and numbers.
    MaxLength: 20
    MinLength: 1
  CustomerProject:
    Description: is used as Customer project tag value for all resources
    Type: String
    Default: CustomerProject
    AllowedPattern: ^[A-Za-z0-9]*$
    ConstraintDescription: must contain only alphanumeric characters and numbers.
    MaxLength: 20
    MinLength: 1
  Environment:
    Description: Environment to deploy. Use staging for limited resources and no alerts.
    Type: String
    Default: Staging
    AllowedValues:
    - Staging
    - Production

Resources:
  DingoQueue: 
    Type: AWS::SQS::Queue
  
  AlarmTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: !Ref AlarmEmail
          Protocol: "email"

  QueueDepthAlarm: 
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmDescription: "Alarm if queue depth grows beyond 10 messages"
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions: 
        - Name: "QueueName"
          Value: !GetAtt DingoQueue.QueueName
      Statistic: "Sum"
      Period: "300"
      EvaluationPeriods: "1"
      Threshold: "10"
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions: 
        - !Ref AlarmTopic
      InsufficientDataActions: 
        - !Ref AlarmTopic

  WebServerGroup: 
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AvailabilityZones: !GetAZs {}
        Fn::GetAZs: ""
      LaunchConfigurationName: 
        Ref: "LaunchConfig"
      MinSize: "2"
      MaxSize: "2"
      LoadBalancerNames: 
        - Ref: "ElasticLoadBalancer"
      MetricsCollection: 
        - Granularity: "1Minute"
          Metrics: 
            - "GroupMinSize"
            - "GroupMaxSize"

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: Boolean
      BlockDeviceMappings:
        - BlockDeviceMapping
      EbsOptimized: Boolean
      IamInstanceProfile: String
      ImageId: String
      InstanceId: String
      InstanceMonitoring: Boolean
      InstanceType: String
      KernelId: String
      KeyName: String
      LaunchConfigurationName: String
      PlacementTenancy: String
      RamDiskId: String
      SecurityGroups:
        - SecurityGroup
      SpotPrice: String
      UserData: String

Outputs:
  